on:
  push:
    branches: master

name: CI
jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Install Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.14.x
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Tests
#        run: go test ./... -cover
#      - name: Integration Tests
#        run: |
#          cd test && ./testRepository.sh && cd ..
#          go test ./... -tags=integration -cover
#  docker:
#    needs: [test]
#    runs-on: ubuntu-latest
#    steps:
#      -
#        name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      -
#        name: Login to GitHub Container Registry
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.CR_PAT }}
#      -
#        name: Build and push
#        id: docker_build
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          tags: ghcr.io/co0p/patchy:latest
#      -
#        name: Image digest
#        run: echo ${{ steps.docker_build.outputs.digest }}
  heroku:
#    needs: [test, docker]
    runs-on: ubuntu-latest
    steps:
      -
        name: login github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: pulling docker image
        run: docker pull ghcr.io/co0p/patchy:latest
      -
        name: logging into heroku registry
        uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}
      -
        name: tagging and pushing container to heroku registry
        run: |
          docker tag ghcr.io/co0p/patchy:latest registry.heroku.com/co0p-patch/web
          docker push registry.heroku.com/co0p-patch/web
      -
        name: create a new heroku release for the docker image
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a co0p-patchy web
